name: Bug Report ðŸž
description: Bugs with PolygonZone
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a PolygonZone Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/roboflow/polygonzone/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the PolygonZone [issues](https://github.com/roboflow/polygonzone/issues) and found no similar bug report.
          required: true

  - type: textarea
    attributes:
      label: Bug
      description: Describe the issue that you are experiencing.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the browser and resolution you are using.
      placeholder: |
        - Browser: [e.g. Chrome, Safari]
        - Resolution: [e.g. 1920x1080] (if your bug relates to the UI at a particular resolution)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        Please provide a list of steps that can be followed to reproduce the bug you have encountered. If a bug is only present when an image is at a particular resolution, note the characteristics of the image (e.g. size, aspect ratio, etc.).
      placeholder: |
        ```
        # Steps to Reproduce
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Information
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/roboflow/polygonzone/pulls) (PR) to help improve PolygonZone for everyone, especially if you have a good understanding of how to implement a fix or a new feature.
      options:
        - label: Yes I'd like to help by submitting a PR!